<a href="https://colab.research.google.com/github/Omkar-Tech24/Student-Performance-Prediction-ML/blob/main/student_performance_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd

data = {
    "study_hours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95],
    "previous_marks": [35, 40, 45, 50, 55, 60, 65, 70, 75, 80],
    "result": [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]  # 0 = Fail, 1 = Pass
}

df = pd.DataFrame(data)
df.to_csv("student_performance_dataset.csv",index=False)
df

   study_hours  attendance  previous_marks  result
0            1          50              35       0
1            2          55              40       0
2            3          60              45       0
3            4          65              50       0
4            5          70              55       1
5            6          75              60       1
6            7          80              65       1
7            8          85              70       1
8            9          90              75       1
9           10          95              80       1

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [24]:
# Load the dataset
df = pd.read_csv("student_performance_dataset.csv")

# Show first 5 rows
df.head()

   study_hours  attendance  previous_marks  result
0            1          50              35       0
1            2          55              40       0
2            3          60              45       0
3            4          65              50       0
4            5          70              55       1

In [25]:
# Feature selection (input and output)
X = df[["study_hours", "attendance", "previous_marks"]]
y = df["result"]

# Split the dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Check shapes
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8, 3), (2, 3), (8,), (2,))

In [26]:
# Create the model
model = DecisionTreeClassifier(random_state=42)

# Train the model using training data
model.fit(X_train, y_train)

print("Model training completed")

Model training completed

In [27]:
# Predict on test data
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 1.0

In [28]:
# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[1 0]
 [0 1]]

In [29]:
# Predict result for a new student using DataFrame (BEST PRACTICE)
new_student = pd.DataFrame(
    [[6, 78, 62]],
    columns=["study_hours", "attendance", "previous_marks"]
)

prediction = model.predict(new_student)

if prediction[0] == 1:
    print("Prediction: Student will PASS")
else:
    print("Prediction: Student will FAIL")

Prediction: Student will PASS